---
- name: "stat: {{ clients_dir }}/{{ item }}"
  stat:
    path: "{{ clients_dir }}/{{ item }}"
  register: stat_path_client

- set_fact:
    openvpn_client_proto_list:
      - "{{ openvpn.proto }}"
      - "{{ openvpn.proto | regex_search('[A-Za-z]+') }}"
    aio_dir: "{{ clients_dir }}/{{ item }}/all-in-one"
    classic_dir: "{{ clients_dir }}/{{ item }}/classic"
    proto: "<unset>"

- when:
    - stat_path_client.failed == false
    - stat_path_client.stat.exists == false
  block:
    - name: "slurp {{ item }}.crt"
      slurp:
        src: "{{ pki_dir }}/issued/{{ item }}.crt"
      register: slurp_client_crt

    - name: "slurp {{ item }}.key"
      slurp:
        src: "{{ pki_dir }}/private/{{ item }}.key"
      register: slurp_client_key

    - name: Remember contents of files
      set_fact:
        ca_text: "{{ slurp_ca_crt['content'] | b64decode | trim }}"
        crt_text: "{{ slurp_client_crt['content'] | b64decode | regex_search('(:?-----BEGIN CERTIFICATE-----((?:\n.+)+)\n-----END CERTIFICATE-----\n?)', multiline=True) | trim }}"
        key_text: "{{ slurp_client_key['content'] | b64decode | trim }}"
        tc_text: "{{ slurp_tc_key['content'] | b64decode | trim }}"
        ta_text: "{{ slurp_ta_key['content'] | b64decode | trim }}"

    - name: "Creating all-in-one directory for client: {{ item }}"
      file:
        path: "{{ aio_dir }}"
        state: directory

    - name: "Creating classic directory for client: {{ item }}"
      file:
        path: "{{ classic_dir }}"
        state: directory

    - name: "set fact: proto = {{ openvpn_client_proto_list[0] }}"
      set_fact:
        proto: "{{ openvpn_client_proto_list[0] }}"

    - name: "Generating all-in-one {{ item }}-{{ proto }}.ovpn"
      template:
        src: roles/openvpn/templates/client.ovpn.j2
        dest: "{{ aio_dir }}/{{ item }}-{{ proto }}.ovpn"

    - name: "Generating classic {{ item }}-{{ proto }}.ovpn"
      template:
        src: roles/openvpn/templates/classic/client.ovpn.j2
        dest: "{{ classic_dir }}/{{ item }}-{{ proto }}.ovpn"

    - name: "set fact: proto = {{ openvpn_client_proto_list[1] }}"
      set_fact:
        proto: "{{ openvpn_client_proto_list[1] }}"

    - name: "Generating all-in-one {{ item }}-{{ proto }}.ovpn"
      when: openvpn_client_proto_list | unique | length == 2
      template:
        src: roles/openvpn/templates/client.ovpn.j2
        dest: "{{ aio_dir }}/{{ item }}-{{ proto }}.ovpn"

    - name: "Generating classic {{ item }}-{{ proto }}.ovpn"
      when: openvpn_client_proto_list | unique | length == 2
      template:
        src: roles/openvpn/templates/classic/client.ovpn.j2
        dest: "{{ classic_dir }}/{{ item }}-{{ proto }}.ovpn"
