---
- name: Installing OpenVPN
  tags: openvpn
  block:
    - import_tasks: install.yml
      tags:
        - install
        - openvpn-install

    - import_tasks: configure/server.yml
      tags:
        - openvpn-server

    - import_tasks: configure/client.yml
      tags:
        - openvpn-client

    - import_tasks: configure/sysctl.yml
      tags:
        - openvpn-server

    - name: start openvpn
      service:
        name: openvpn
        state: started

    - name: "start openvpn@{{ openvpn.instance }}"
      service:
        name: 'openvpn@{{ openvpn.instance }}'
        state: started
