---
- name: Installing OpenVPN
  tags: openvpn
  block:
    - import_tasks: install.yml
      tags:
        - install
        - openvpn-install

    - import_tasks: configure-server.yml
      tags:
        - openvpn-server

    - import_tasks: configure-client.yml
      tags:
        - openvpn-client

    - name: start openvpn
      service:
        name: openvpn
        state: started
